import type { FeaturedHeroItem, VideoItem } from "./types";

/**
 * Real YouTube video IDs from premium creators.
 * Thumbnails are loaded directly from i.ytimg.com (always available, no API key needed).
 */
const yt = (id: string) => `https://i.ytimg.com/vi/${id}/maxresdefault.jpg`;
const ytHQ = (id: string) => `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;

export const MOCK_VIDEOS: Record<string, VideoItem[]> = {
  spotlight: [
    {
      id: "uD4izuDMUQA",
      title: "TIMELAPSE OF THE FUTURE: A Journey to the End of Time",
      channelTitle: "melodysheep",
      channelId: "UC51t3aCqXzVf1n9v_Nf2V3w",
      publishedAt: "2019-03-20",
      duration: "29:20",
      durationSeconds: 1760,
      viewCount: 50_200_000,
      thumbnail: yt("uD4izuDMUQA"),
      backdrop: yt("uD4izuDMUQA"),
      description: "How is it all going to end? We start in 2019 and travel exponentially through time, witnessing the future of Earth, the death of all stars, and proton decay.",
      tags: ["space", "future", "science"],
    },
    {
      id: "HwAPLk_sQ3w",
      title: "THE AMAZING DIGITAL CIRCUS: PILOT",
      channelTitle: "GLITCH",
      channelId: "UC0b-S9R34y_2qX4s5t4Qp1Q",
      publishedAt: "2023-10-13",
      duration: "25:01",
      durationSeconds: 1501,
      viewCount: 345_000_000,
      thumbnail: yt("HwAPLk_sQ3w"),
      backdrop: yt("HwAPLk_sQ3w"),
      description: "A woman gets trapped in a wacky virtual world along with five other humans and is now at the mercy of a wacky AI.",
      tags: ["animation", "surreal", "comedy"],
    },
    {
      id: "L45Q1_psDqk",
      title: "Is Anything Real?",
      channelTitle: "Vsauce",
      channelId: "UC6nSFpj9HTCZ5t4N3Rm3v1g",
      publishedAt: "2018-06-25",
      duration: "23:44",
      durationSeconds: 1424,
      viewCount: 24_500_000,
      thumbnail: yt("L45Q1_psDqk"),
      backdrop: yt("L45Q1_psDqk"),
      description: "An exploration of reality, solipsism, consciousness, and the physics of what we perceive as real.",
      tags: ["philosophy", "science"],
    },
    {
      id: "LxgMdjyw8uw",
      title: "The Bizarre Behavior of Rotating Bodies",
      channelTitle: "Veritasium",
      channelId: "UCHnyfMqiRRG1u-2MsSQLbXA",
      publishedAt: "2019-09-19",
      duration: "07:30",
      durationSeconds: 450,
      viewCount: 35_400_000,
      thumbnail: yt("1VPfZ_XzisU"),
      backdrop: yt("1VPfZ_XzisU"),
      description:
        "The Dzhanibekov effect, or tennis racket theorem — why a spinning object flips over and over in zero gravity.",
      tags: ["physics", "space"],
    },
    {
      id: "lFEgohhfxOA",
      title: "The Egg — A Short Story",
      channelTitle: "Kurzgesagt – In a Nutshell",
      channelId: "UCsXVk37bltHxD1rDPwtNM8Q",
      publishedAt: "2019-11-30",
      duration: "07:55",
      durationSeconds: 475,
      viewCount: 90_200_000,
      thumbnail: yt("h6fcK_fRYaI"),
      backdrop: yt("h6fcK_fRYaI"),
      description: "A short story by Andy Weir, animated. A meditation on death, life, and being everyone.",
      tags: ["animation", "philosophy"],
    },
    {
      id: "0e3GPea1Tyg",
      title: "How Wolves Change Rivers",
      channelTitle: "Vox",
      channelId: "UCLXo7UDZvByw2ixzpQCufnA",
      publishedAt: "2020-04-15",
      duration: "11:24",
      durationSeconds: 684,
      viewCount: 18_700_000,
      thumbnail: yt("ysa5OBhXz-Q"),
      backdrop: yt("ysa5OBhXz-Q"),
      description:
        "When wolves were reintroduced to Yellowstone, they didn't just change the elk population — they changed the geography of the park itself.",
      tags: ["nature", "ecology"],
    },
  ],
  animation: [
    {
      id: "HwAPLk_sQ3w",
      title: "THE AMAZING DIGITAL CIRCUS: PILOT",
      channelTitle: "GLITCH",
      channelId: "UC0b-S9R34y_2qX4s5t4Qp1Q",
      publishedAt: "2023-10-13",
      duration: "25:01",
      durationSeconds: 1501,
      viewCount: 345_000_000,
      thumbnail: yt("HwAPLk_sQ3w"),
      backdrop: yt("HwAPLk_sQ3w"),
      description: "A woman gets trapped in a wacky virtual world along with five other humans and is now at the mercy of a wacky AI.",
      tags: ["animation", "surreal", "comedy"],
    },
    {
      id: "4ofJpOEXrZs",
      title: "THE AMAZING DIGITAL CIRCUS - Ep 2: Candy Carrier Chaos!",
      channelTitle: "GLITCH",
      channelId: "UC0b-S9R34y_2qX4s5t4Qp1Q",
      publishedAt: "2024-05-03",
      duration: "25:52",
      durationSeconds: 1552,
      viewCount: 124_000_000,
      thumbnail: yt("4ofJpOEXrZs"),
      backdrop: yt("4ofJpOEXrZs"),
      description: "Our cast of wacky characters embark on a candy-fueled high-speed truck heist.",
      tags: ["animation", "indie", "comedy"],
    },
    {
      id: "hMYojv0Te1k",
      title: "MURDER DRONES - Episode 1: PILOT",
      channelTitle: "GLITCH",
      channelId: "UC0b-S9R34y_2qX4s5t4Qp1Q",
      publishedAt: "2021-10-29",
      duration: "26:33",
      durationSeconds: 1593,
      viewCount: 52_000_000,
      thumbnail: yt("hMYojv0Te1k"),
      backdrop: yt("hMYojv0Te1k"),
      description: "In a post-apocalyptic frozen planet, worker drones struggle to survive against rogue disassembly drones.",
      tags: ["animation", "action", "sci-fi"],
    },
    {
      id: "lFEgohhfxOA",
      title: "The Egg — A Short Story",
      channelTitle: "Kurzgesagt – In a Nutshell",
      channelId: "UCsXVk37bltHxD1rDPwtNM8Q",
      publishedAt: "2019-11-30",
      duration: "07:55",
      durationSeconds: 475,
      viewCount: 90_200_000,
      thumbnail: yt("h6fcK_fRYaI"),
      backdrop: yt("h6fcK_fRYaI"),
      description: "A short story by Andy Weir, animated. A meditation on death, life, and being everyone.",
      tags: ["animation", "philosophy"],
    },
  ],
  science: [
    {
      id: "L45Q1_psDqk",
      title: "Is Anything Real?",
      channelTitle: "Vsauce",
      channelId: "UC6nSFpj9HTCZ5t4N3Rm3v1g",
      publishedAt: "2018-06-25",
      duration: "23:44",
      durationSeconds: 1424,
      viewCount: 24_500_000,
      thumbnail: yt("L45Q1_psDqk"),
      backdrop: yt("L45Q1_psDqk"),
      description: "An exploration of reality, solipsism, consciousness, and the physics of what we perceive as real.",
      tags: ["philosophy", "science"],
    },
    {
      id: "uD4izuDMUQA",
      title: "TIMELAPSE OF THE FUTURE: A Journey to the End of Time",
      channelTitle: "melodysheep",
      channelId: "UC51t3aCqXzVf1n9v_Nf2V3w",
      publishedAt: "2019-03-20",
      duration: "29:20",
      durationSeconds: 1760,
      viewCount: 50_200_000,
      thumbnail: yt("uD4izuDMUQA"),
      backdrop: yt("uD4izuDMUQA"),
      description: "How is it all going to end? We start in 2019 and travel exponentially through time, witnessing the future of Earth, the death of all stars, and proton decay.",
      tags: ["space", "future", "science"],
    },
    {
      id: "dX9CGRZwD-w",
      title: "How do CPUs Work? (The Engineering that Runs the Digital World)",
      channelTitle: "Branch Education",
      channelId: "UCDPu84k26pLhG9K3aP0aK_g",
      publishedAt: "2021-08-20",
      duration: "20:30",
      durationSeconds: 1230,
      viewCount: 12_400_000,
      thumbnail: yt("dX9CGRZwD-w"),
      backdrop: yt("dX9CGRZwD-w"),
      description: "A deep dive using detailed 3D animations into the architecture, transistors, and logic gates that power a CPU.",
      tags: ["engineering", "hardware"],
    },
    {
      id: "spUNpyF58BY",
      title: "But what is a Fourier Transform? A visual introduction.",
      channelTitle: "3Blue1Brown",
      channelId: "UCYO_jab_esuFRV4b17AJtAw",
      publishedAt: "2018-01-26",
      duration: "20:56",
      durationSeconds: 1256,
      viewCount: 11_300_000,
      thumbnail: yt("spUNpyF58BY"),
      backdrop: yt("spUNpyF58BY"),
      description: "An animated introduction to the Fourier Transform, showing how we can break signals into frequency components.",
      tags: ["math", "visual"],
    },
    {
      id: "E7Up7VuFd8A",
      title: "How Do SSDs Work? (Solid State Drives Explained)",
      channelTitle: "Branch Education",
      channelId: "UCDPu84k26pLhG9K3aP0aK_g",
      publishedAt: "2023-02-15",
      duration: "23:42",
      durationSeconds: 1422,
      viewCount: 5_100_000,
      thumbnail: yt("E7Up7VuFd8A"),
      backdrop: yt("E7Up7VuFd8A"),
      description: "Explore the nanometer-scale architecture of NAND Flash memory and how floating gate transistors store data without power.",
      tags: ["engineering", "hardware"],
    },
    {
      id: "fCn8zs912OE",
      title: "The Zipf Mystery",
      channelTitle: "Vsauce",
      channelId: "UC6nSFpj9HTCZ5t4N3Rm3v1g",
      publishedAt: "2015-09-15",
      duration: "20:53",
      durationSeconds: 1253,
      viewCount: 30_800_000,
      thumbnail: yt("fCn8zs912OE"),
      backdrop: yt("fCn8zs912OE"),
      description: "Why does the most common word in English occur twice as often as the second most common word? Introducing Zipf's Law.",
      tags: ["linguistics", "math"],
    },
    {
      id: "1VPfZ_XzisU",
      title: "The Bizarre Behavior of Rotating Bodies, Explained",
      channelTitle: "Veritasium",
      channelId: "UCHnyfMqiRRG1u-2MsSQLbXA",
      publishedAt: "2019-09-19",
      duration: "07:30",
      durationSeconds: 450,
      viewCount: 35_400_000,
      thumbnail: yt("1VPfZ_XzisU"),
      tags: ["physics"],
    },
    {
      id: "h6fcK_fRYaI",
      title: "Geometry of a Black Hole",
      channelTitle: "Kurzgesagt – In a Nutshell",
      channelId: "UCsXVk37bltHxD1rDPwtNM8Q",
      publishedAt: "2024-09-19",
      duration: "10:22",
      durationSeconds: 622,
      viewCount: 12_400_000,
      thumbnail: yt("h6fcK_fRYaI"),
      tags: ["space"],
    },
  ],
  essays: [
    {
      id: "DwmIK7QPM2g",
      title: "How Pixar Uses Music to Make You Cry",
      channelTitle: "Nerdwriter1",
      channelId: "UCJIfeSCssxSC_Dhc5s7woww",
      publishedAt: "2020-05-12",
      duration: "07:42",
      durationSeconds: 462,
      viewCount: 3_800_000,
      thumbnail: yt("DwmIK7QPM2g"),
      tags: ["film"],
    },
    {
      id: "FdSN4McPgM4",
      title: "Radiohead's Most Mathematical Song",
      channelTitle: "Polyphonic",
      channelId: "UC2T8m5EAvWamBYO0nMo3jqQ",
      publishedAt: "2018-04-04",
      duration: "12:18",
      durationSeconds: 738,
      viewCount: 4_900_000,
      thumbnail: yt("zGDzdps75ns"),
      tags: ["music"],
    },
    {
      id: "ddT_F2Wj9C0",
      title: "Why Maps Lie",
      channelTitle: "Johnny Harris",
      channelId: "UCmGSJVG3mCRXVOP4yZrU1Dw",
      publishedAt: "2022-08-08",
      duration: "14:11",
      durationSeconds: 851,
      viewCount: 7_600_000,
      thumbnail: yt("xvQUiX26RfE"),
      tags: ["geography"],
    },
    {
      id: "uVnUq6CkFOY",
      title: "The Genius of Christopher Nolan's Editing",
      channelTitle: "Nerdwriter1",
      channelId: "UCJIfeSCssxSC_Dhc5s7woww",
      publishedAt: "2021-09-18",
      duration: "09:32",
      durationSeconds: 572,
      viewCount: 2_100_000,
      thumbnail: yt("uVnUq6CkFOY"),
      tags: ["film"],
    },
    {
      id: "zGDzdps75ns",
      title: "Pink Floyd's 'Echoes' — A Mini-Symphony",
      channelTitle: "Polyphonic",
      channelId: "UC2T8m5EAvWamBYO0nMo3jqQ",
      publishedAt: "2019-02-15",
      duration: "15:21",
      durationSeconds: 921,
      viewCount: 3_200_000,
      thumbnail: yt("zGDzdps75ns"),
      tags: ["music"],
    },
    {
      id: "xvQUiX26RfE",
      title: "Why I'm Leaving Vox",
      channelTitle: "Johnny Harris",
      channelId: "UCmGSJVG3mCRXVOP4yZrU1Dw",
      publishedAt: "2021-04-30",
      duration: "08:14",
      durationSeconds: 494,
      viewCount: 5_800_000,
      thumbnail: yt("xvQUiX26RfE"),
      tags: ["journalism"],
    },
  ],
  world: [
    {
      id: "ysa5OBhXz-Q",
      title: "How Wolves Change Rivers",
      channelTitle: "Vox",
      channelId: "UCLXo7UDZvByw2ixzpQCufnA",
      publishedAt: "2020-04-15",
      duration: "11:24",
      durationSeconds: 684,
      viewCount: 18_700_000,
      thumbnail: yt("ysa5OBhXz-Q"),
      tags: ["nature"],
    },
    {
      id: "PJTBQikuMaI",
      title: "Why Cities Exist",
      channelTitle: "Wendover Productions",
      channelId: "UC9RM-iSvTu1uPJb8X5yp3EQ",
      publishedAt: "2018-08-21",
      duration: "08:58",
      durationSeconds: 538,
      viewCount: 6_200_000,
      thumbnail: yt("PJTBQikuMaI"),
      tags: ["cities"],
    },
    {
      id: "GwT-DCwbQ_E",
      title: "How One Line in the Constitution Shaped America",
      channelTitle: "Johnny Harris",
      channelId: "UCmGSJVG3mCRXVOP4yZrU1Dw",
      publishedAt: "2023-07-04",
      duration: "16:02",
      durationSeconds: 962,
      viewCount: 4_400_000,
      thumbnail: yt("GwT-DCwbQ_E"),
      tags: ["history"],
    },
    {
      id: "JE0lkVuoZcU",
      title: "How the World's Tallest Skyscraper Was Built",
      channelTitle: "Real Engineering",
      channelId: "UCR1IuLEqb6UEA_zQ81kwXfg",
      publishedAt: "2022-10-09",
      duration: "13:50",
      durationSeconds: 830,
      viewCount: 3_100_000,
      thumbnail: yt("JE0lkVuoZcU"),
      tags: ["engineering"],
    },
    {
      id: "y8XvQNt26KI",
      title: "Why Japan's Population Is Shrinking",
      channelTitle: "Vox",
      channelId: "UCLXo7UDZvByw2ixzpQCufnA",
      publishedAt: "2023-05-22",
      duration: "12:48",
      durationSeconds: 768,
      viewCount: 5_700_000,
      thumbnail: yt("y8XvQNt26KI"),
      tags: ["demography"],
    },
    {
      id: "vNHe5DKd8eg",
      title: "How Singapore Became an Economic Miracle",
      channelTitle: "Wendover Productions",
      channelId: "UC9RM-iSvTu1uPJb8X5yp3EQ",
      publishedAt: "2024-01-17",
      duration: "19:35",
      durationSeconds: 1175,
      viewCount: 2_800_000,
      thumbnail: yt("vNHe5DKd8eg"),
      tags: ["economics"],
    },
  ],
  design: [
    {
      id: "Os2QcRT8a-c",
      title: "iPhone 16 Pro Review: The Subtle Year",
      channelTitle: "Marques Brownlee",
      channelId: "UCBJycsmduvYEL83R_U4JriQ",
      publishedAt: "2024-09-20",
      duration: "18:24",
      durationSeconds: 1104,
      viewCount: 12_500_000,
      thumbnail: yt("Os2QcRT8a-c"),
      tags: ["tech"],
    },
    {
      id: "xoxhDk-hwzs",
      title: "Glitter Bomb vs. Package Thief",
      channelTitle: "Mark Rober",
      channelId: "UCY1kMZp36IQSyNx_9h4mpCg",
      publishedAt: "2018-12-17",
      duration: "11:27",
      durationSeconds: 687,
      viewCount: 88_900_000,
      thumbnail: yt("xoxhDk-hwzs"),
      backdrop: yt("xoxhDk-hwzs"),
      description: "An engineered revenge device is disguised as a parcel to catch package thieves with glitter and fart spray.",
      tags: ["engineering", "fun"],
    },
    {
      id: "F8L5tD4LZ-w",
      title: "Inside Tadao Ando's Most Famous Building",
      channelTitle: "ArchDaily",
      channelId: "UC9pVZsQq8L3rHFJ52uX8Yvg",
      publishedAt: "2023-11-12",
      duration: "11:08",
      durationSeconds: 668,
      viewCount: 1_900_000,
      thumbnail: yt("F8L5tD4LZ-w"),
      tags: ["architecture"],
    },
    {
      id: "wVyu7NB7W3Y",
      title: "How Apple Designs Software, Explained by an Insider",
      channelTitle: "Marques Brownlee",
      channelId: "UCBJycsmduvYEL83R_U4JriQ",
      publishedAt: "2024-06-12",
      duration: "32:55",
      durationSeconds: 1975,
      viewCount: 8_400_000,
      thumbnail: yt("wVyu7NB7W3Y"),
      tags: ["design"],
    },
    {
      id: "VgVQKCcfwnU",
      title: "Inside a 14-Course Tasting Menu in Tokyo",
      channelTitle: "Bon Appétit",
      channelId: "UCbpMy0Fg74eXXkvxJrtEn3w",
      publishedAt: "2024-03-08",
      duration: "22:14",
      durationSeconds: 1334,
      viewCount: 4_100_000,
      thumbnail: yt("VgVQKCcfwnU"),
      tags: ["food"],
    },
    {
      id: "NXkE4nYrK7Q",
      title: "Why Brutalism Is Coming Back",
      channelTitle: "ArchDaily",
      channelId: "UC9pVZsQq8L3rHFJ52uX8Yvg",
      publishedAt: "2024-05-04",
      duration: "12:48",
      durationSeconds: 768,
      viewCount: 2_100_000,
      thumbnail: yt("NXkE4nYrK7Q"),
      tags: ["architecture"],
    },
  ],
  nature: [
    {
      id: "1VPfZ_XzisU",
      title: "The Blue Planet's Most Surprising Inhabitants",
      channelTitle: "National Geographic",
      channelId: "UCpVm7bg6pXKo1Pr6k5kxG9A",
      publishedAt: "2024-04-22",
      duration: "21:00",
      durationSeconds: 1260,
      viewCount: 7_900_000,
      thumbnail: yt("1VPfZ_XzisU"),
      tags: ["ocean"],
    },
    {
      id: "h6fcK_fRYaI",
      title: "What Happens If We Lose All Insects?",
      channelTitle: "Kurzgesagt – In a Nutshell",
      channelId: "UCsXVk37bltHxD1rDPwtNM8Q",
      publishedAt: "2023-06-14",
      duration: "10:11",
      durationSeconds: 611,
      viewCount: 18_300_000,
      thumbnail: yt("h6fcK_fRYaI"),
      tags: ["ecology"],
    },
    {
      id: "ysa5OBhXz-Q",
      title: "The Quiet Architecture of Tide Pools",
      channelTitle: "National Geographic",
      channelId: "UCpVm7bg6pXKo1Pr6k5kxG9A",
      publishedAt: "2025-08-09",
      duration: "12:48",
      durationSeconds: 768,
      viewCount: 1_200_000,
      thumbnail: yt("ysa5OBhXz-Q"),
      tags: ["ocean"],
    },
    {
      id: "y8XvQNt26KI",
      title: "Inside the Vanishing Glaciers of Patagonia",
      channelTitle: "National Geographic",
      channelId: "UCpVm7bg6pXKo1Pr6k5kxG9A",
      publishedAt: "2023-10-28",
      duration: "28:33",
      durationSeconds: 1713,
      viewCount: 4_400_000,
      thumbnail: yt("y8XvQNt26KI"),
      tags: ["climate"],
    },
    {
      id: "H6u0VBqNBQ8",
      title: "The Secret Life of Trees",
      channelTitle: "Kurzgesagt – In a Nutshell",
      channelId: "UCsXVk37bltHxD1rDPwtNM8Q",
      publishedAt: "2024-02-29",
      duration: "11:46",
      durationSeconds: 706,
      viewCount: 9_500_000,
      thumbnail: yt("H6u0VBqNBQ8"),
      tags: ["forest"],
    },
  ],
  art: [
    {
      id: "BMOSSEM5tPo",
      title: "Vermeer's 'Girl with a Pearl Earring' — Explained",
      channelTitle: "The Great Art Explained",
      channelId: "UCD-miitqNY3nyukJ4Fnf4_A",
      publishedAt: "2022-12-02",
      duration: "16:08",
      durationSeconds: 968,
      viewCount: 2_900_000,
      thumbnail: yt("BMOSSEM5tPo"),
      tags: ["art"],
    },
    {
      id: "Pt6FSNG-eYg",
      title: "Caravaggio: The Painter Who Got Away With Murder",
      channelTitle: "The Great Art Explained",
      channelId: "UCD-miitqNY3nyukJ4Fnf4_A",
      publishedAt: "2023-04-18",
      duration: "18:42",
      durationSeconds: 1122,
      viewCount: 1_800_000,
      thumbnail: yt("Pt6FSNG-eYg"),
      tags: ["art"],
    },
    {
      id: "uVnUq6CkFOY",
      title: "How Hokusai Made the Greatest Wave Ever Drawn",
      channelTitle: "Nerdwriter1",
      channelId: "UCJIfeSCssxSC_Dhc5s7woww",
      publishedAt: "2020-11-09",
      duration: "10:17",
      durationSeconds: 617,
      viewCount: 4_200_000,
      thumbnail: yt("uVnUq6CkFOY"),
      tags: ["art"],
    },
    {
      id: "DwmIK7QPM2g",
      title: "Why Rothko Made People Cry",
      channelTitle: "Nerdwriter1",
      channelId: "UCJIfeSCssxSC_Dhc5s7woww",
      publishedAt: "2018-07-25",
      duration: "08:33",
      durationSeconds: 513,
      viewCount: 3_400_000,
      thumbnail: yt("DwmIK7QPM2g"),
      tags: ["art"],
    },
    {
      id: "F8L5tD4LZ-w",
      title: "The Architecture of the Pantheon, in 12 Minutes",
      channelTitle: "ArchDaily",
      channelId: "UC9pVZsQq8L3rHFJ52uX8Yvg",
      publishedAt: "2024-08-15",
      duration: "12:02",
      durationSeconds: 722,
      viewCount: 1_100_000,
      thumbnail: yt("F8L5tD4LZ-w"),
      tags: ["architecture"],
    },
  ],
};

export const MOCK_HERO: FeaturedHeroItem[] = [
  {
    id: "uD4izuDMUQA",
    title: "Timelapse of the Future",
    tagline: "A Journey to the End of Time",
    channelTitle: "melodysheep",
    channelId: "UC51t3aCqXzVf1n9v_Nf2V3w",
    publishedAt: "2019-03-20",
    duration: "29:20",
    durationSeconds: 1760,
    viewCount: 50_200_000,
    thumbnail: yt("uD4izuDMUQA"),
    backdrop: yt("uD4izuDMUQA"),
    description: "How is it all going to end? We start in 2019 and travel exponentially through time, witnessing the future of Earth, the death of all stars, proton decay, and the final state of our universe.",
    tint: "#ec4899",
    tags: ["Space", "Future", "Science"],
  },
  {
    id: "HwAPLk_sQ3w",
    title: "The Amazing Digital Circus",
    tagline: "Ep 1: Pilot",
    channelTitle: "GLITCH",
    channelId: "UC0b-S9R34y_2qX4s5t4Qp1Q",
    publishedAt: "2023-10-13",
    duration: "25:01",
    durationSeconds: 1501,
    viewCount: 345_000_000,
    thumbnail: yt("HwAPLk_sQ3w"),
    backdrop: yt("HwAPLk_sQ3w"),
    description: "A woman gets trapped in a wacky virtual world along with five other humans and is now at the mercy of a wacky AI and their own personal traumas.",
    tint: "#ef4444",
    tags: ["Animation", "Surreal", "Comedy"],
  },
  {
    id: "lFEgohhfxOA",
    title: "The Egg",
    tagline: "A Short Story",
    channelTitle: "Kurzgesagt – In a Nutshell",
    channelId: "UCsXVk37bltHxD1rDPwtNM8Q",
    publishedAt: "2019-11-30",
    duration: "07:55",
    durationSeconds: 475,
    viewCount: 90_200_000,
    thumbnail: yt("h6fcK_fRYaI"),
    backdrop: yt("h6fcK_fRYaI"),
    description:
      "You were on your way home when you died. It was a car accident. Nothing particularly remarkable, but fatal nonetheless. A short story by Andy Weir, animated.",
    tint: "#8b5cf6",
    tags: ["Animation", "Philosophy"],
  },
  {
    id: "LxgMdjyw8uw",
    title: "Bizarre Behavior of Rotating Bodies",
    tagline: "A spinning paradox in zero gravity",
    channelTitle: "Veritasium",
    channelId: "UCHnyfMqiRRG1u-2MsSQLbXA",
    publishedAt: "2019-09-19",
    duration: "07:30",
    durationSeconds: 450,
    viewCount: 35_400_000,
    thumbnail: yt("1VPfZ_XzisU"),
    backdrop: yt("1VPfZ_XzisU"),
    description:
      "Why does a rotating handle flip over and over by itself in zero gravity? Cosmonaut Vladimir Dzhanibekov discovered this on Mir — and the explanation rewrote what we thought we knew.",
    tint: "#3b82f6",
    tags: ["Physics", "Space"],
  },
];

/** Flat lookup by video id (used by the watch page). */
export const VIDEO_INDEX: Record<string, VideoItem> = (() => {
  const idx: Record<string, VideoItem> = {};
  for (const r of Object.values(MOCK_VIDEOS)) for (const v of r) idx[v.id] = v;
  for (const v of MOCK_HERO) idx[v.id] = v;
  return idx;
})();

export function getVideo(id: string): VideoItem | undefined {
  return VIDEO_INDEX[id];
}

export function getRelated(channelId: string, excludeId: string, limit = 6): VideoItem[] {
  const all = Object.values(MOCK_VIDEOS).flat();
  const sameChannel = all.filter((v) => v.channelId === channelId && v.id !== excludeId);
  const others = all.filter((v) => v.channelId !== channelId && v.id !== excludeId);
  return [...sameChannel, ...others].slice(0, limit);
}

export { ytHQ };
